version: "3.9"

services:
  nginx:
    restart: always
    container_name: info21_nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    tty: true
    stdin_open: true


  postgres:
    container_name: info21_db
    build:
      context: .
      dockerfile: Dockerfile_postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    tty: true
    stdin_open: true


  java:
    container_name: info21_app
    build:
      context: .
      dockerfile: Dockerfile_java
    volumes:
      - ./logs:/project/logs
    depends_on:
      - nginx
      - postgres
    tty: true
    stdin_open: true

